version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "4002:4002"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: my-secret-pw
      DB_DATABASE: invoices
      DB_PORT: 3306
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    networks:
      - loki_network
    volumes:
      - ./app-logs:/var/log/app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: invoices
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-logs:/var/log/mysql
    networks:
      - loki_network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-logs:/var/log/redis
    networks:
      - loki_network

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki_network

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./app-logs:/var/log/app
      - ./mysql-logs:/var/log/mysql
      - ./redis-logs:/var/log/redis
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - loki_network

volumes:
  db-data:
  loki-data:

networks:
  loki_network:
    driver: bridge
